version: '3.1'

services:

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: joshua
      MONGO_INITDB_ROOT_PASSWORD: test
    ports: 
      - '27017:27017'

  #  mongodb://joshua:test@mongo:27017/